spring.application.name=Eureka-Server

# Server port
server.port=8761


# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: reduce startup wait time
eureka.server.wait-time-in-ms-when-sync-empty=0
